FROM python:3.11

RUN apt-get update && apt-get install -y \
	libpcap0.8-dev \
	libuv1-dev

RUN pip install --no-cache-dir --upgrade pip

RUN python3 -m pip install --upgrade pip setuptools wheel pip-tools

COPY prueba.py /

COPY requirements.in /

RUN pip-compile --output-file=requirements.txt requirements.in

RUN pip install -r requirements.txt

CMD "python3" "/prueba.py"
